[package]
name = "twozero48"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[dependencies]
nalgebra = "*"
termion = "1"
rand = "0.7"

[[bin]]
name = "twozero48"
path = "src/main.rs"