Output assets/demo.gif

Require target/debug/twozero48

Set Shell "zsh"
Set Theme "OneDark"
Set Width 1000
Set Height 800
Set FontSize 22
Set LetterSpacing 0
Set LineHeight 1.2
Set Padding 4
Set Framerate 24
Set TypingSpeed 1ms

Hide
Type "env -u NO_COLOR COLORTERM=truecolor TERM=xterm-256color ./target/debug/twozero48"
Enter
Sleep 2s

Show
Sleep 1.5s

Right
Sleep 750ms
Down
Sleep 750ms
Left
Sleep 750ms
Up
Sleep 750ms
Right
Sleep 750ms
Down
Sleep 1000ms
Left
Sleep 750ms
Up
Sleep 750ms
Right
Sleep 750ms
Down
Sleep 750ms
Left
Sleep 750ms
Up
Sleep 750ms
Right
Sleep 750ms
Down
Sleep 750ms
Left
Sleep 750ms
Up
Sleep 1000ms
Left
Sleep 750ms
Up
Sleep 750ms
Right
Sleep 750ms
Down
Sleep 750ms

Sleep 1.5s
Hide
Escape
Sleep 250ms
